import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const OUT_DIR = join(ROOT, 'src', 'lib', 'i18n', 'generated');

// Source directory → BCP 47 language code for output filenames
const LANG_SRC_MAP = { zh: 'zh-Hans', en: 'en' };
const SRC_DIRS = Object.keys(LANG_SRC_MAP);

function readJSON(path) {
	return JSON.parse(readFileSync(path, 'utf-8'));
}

function mergeLocales(srcDir) {
	const web = readJSON(join(ROOT, 'src', 'locales', srcDir, 'web.json'));
	const code = LANG_SRC_MAP[srcDir];
	return [code, web];
}

function validateKeys(merged, codes) {
	for (const code of codes) {
		const data = merged[code];
		for (const [key, value] of Object.entries(data)) {
			if (!value || value.trim() === '') {
				console.error(`[i18n] Empty value for key "${key}" in ${code}`);
				process.exit(1);
			}
			if (value === key) {
				console.error(`[i18n] Untranslated key "${key}" in ${code} (value equals key)`);
				process.exit(1);
			}
		}
	}
}

function validateSymmetry(merged, codes) {
	const keysByLang = {};
	for (const code of codes) {
		keysByLang[code] = new Set(Object.keys(merged[code]));
	}
	const allKeys = new Set([...keysByLang[codes[0]], ...keysByLang[codes[1]]]);
	for (const key of allKeys) {
		for (const code of codes) {
			if (!keysByLang[code].has(key)) {
				console.error(`[i18n] Key "${key}" exists in some languages but missing in ${code}`);
				process.exit(1);
			}
		}
	}
}

function validatePlaceholders(merged, codes) {
	for (const key of Object.keys(merged[codes[0]])) {
		const placeholders = new Set();
		for (const code of codes) {
			const value = merged[code][key];
			const matches = value.match(/\{(\w+)\}/g) || [];
			for (const m of matches) {
				placeholders.add(m);
			}
		}
		for (const code of codes) {
			const value = merged[code][key];
			for (const ph of placeholders) {
				if (!value.includes(ph)) {
					console.error(`[i18n] Placeholder ${ph} mismatch in key "${key}" (${code}: "${value}")`);
					process.exit(1);
				}
			}
		}
	}
}

function generateTypes(merged, codes) {
	const keys = Object.keys(merged[codes[0]]).sort();
	const union = keys.map((k) => `  | '${k}'`).join('\n');
	return [
		'// Auto-generated by scripts/merge-locales.mjs — DO NOT EDIT',
		`// Generated at: ${new Date().toISOString()}`,
		'',
		`export type TranslationKey =`,
		union + ';',
		''
	].join('\n');
}

function main() {
	mkdirSync(OUT_DIR, { recursive: true });

	const codes = Object.values(LANG_SRC_MAP);
	const merged = {};
	for (const srcDir of SRC_DIRS) {
		const [code, data] = mergeLocales(srcDir);
		merged[code] = data;
		const outPath = join(OUT_DIR, `${code}.json`);
		writeFileSync(outPath, JSON.stringify(data, null, 2) + '\n');
		console.log(`[i18n] Written: ${outPath} (${Object.keys(data).length} keys)`);
	}

	// Validate
	validateKeys(merged, codes);
	validateSymmetry(merged, codes);
	validatePlaceholders(merged, codes);

	// Generate types
	const typesContent = generateTypes(merged, codes);
	writeFileSync(join(OUT_DIR, 'keys.ts'), typesContent);
	console.log(`[i18n] Generated types: ${join(OUT_DIR, 'keys.ts')}`);
}

main();
