import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const REPO_ROOT = join(ROOT, '..');
const OUT_DIR = join(ROOT, 'src', 'lib', 'i18n', 'generated');

const LANGS = ['zh', 'en'];

function readJSON(path) {
  return JSON.parse(readFileSync(path, 'utf-8'));
}

function mergeLocales(lang) {
  const common = readJSON(join(REPO_ROOT, 'locales', lang, 'common.json'));
  const web = readJSON(join(ROOT, 'src', 'locales', lang, 'web.json'));
  return { ...common, ...web };
}

function validateKeys(merged) {
  for (const lang of LANGS) {
    const data = merged[lang];
    for (const [key, value] of Object.entries(data)) {
      if (!value || value.trim() === '') {
        console.error(`[i18n] Empty value for key "${key}" in ${lang}`);
        process.exit(1);
      }
      if (value === key) {
        console.error(`[i18n] Untranslated key "${key}" in ${lang} (value equals key)`);
        process.exit(1);
      }
    }
  }
}

function validateSymmetry(merged) {
  const keysByLang = {};
  for (const lang of LANGS) {
    keysByLang[lang] = new Set(Object.keys(merged[lang]));
  }
  const allKeys = new Set([...keysByLang[LANGS[0]], ...keysByLang[LANGS[1]]]);
  for (const key of allKeys) {
    for (const lang of LANGS) {
      if (!keysByLang[lang].has(key)) {
        console.error(`[i18n] Key "${key}" exists in some languages but missing in ${lang}`);
        process.exit(1);
      }
    }
  }
}

function validatePlaceholders(merged) {
  for (const key of Object.keys(merged[LANGS[0]])) {
    const placeholders = new Set();
    for (const lang of LANGS) {
      const value = merged[lang][key];
      const matches = value.match(/\{(\w+)\}/g) || [];
      for (const m of matches) {
        placeholders.add(m);
      }
    }
    for (const lang of LANGS) {
      const value = merged[lang][key];
      for (const ph of placeholders) {
        if (!value.includes(ph)) {
          console.error(
            `[i18n] Placeholder ${ph} mismatch in key "${key}" (${lang}: "${value}")`
          );
          process.exit(1);
        }
      }
    }
  }
}

function generateTypes(merged) {
  const keys = Object.keys(merged[LANGS[0]]).sort();
  const union = keys.map((k) => `  | '${k}'`).join('\n');
  return [
    '// Auto-generated by scripts/merge-locales.mjs — DO NOT EDIT',
    `// Generated at: ${new Date().toISOString()}`,
    '',
    `export type TranslationKey =`,
    union + ';',
    '',
  ].join('\n');
}

function main() {
  mkdirSync(OUT_DIR, { recursive: true });

  const merged = {};
  for (const lang of LANGS) {
    merged[lang] = mergeLocales(lang);
    const outPath = join(OUT_DIR, `${lang}.json`);
    writeFileSync(outPath, JSON.stringify(merged[lang], null, 2) + '\n');
    console.log(`[i18n] Written: ${outPath} (${Object.keys(merged[lang]).length} keys)`);
  }

  // Validate
  validateKeys(merged);
  validateSymmetry(merged);
  validatePlaceholders(merged);

  // Generate types
  const typesContent = generateTypes(merged);
  writeFileSync(join(OUT_DIR, 'keys.ts'), typesContent);
  console.log(`[i18n] Generated types: ${join(OUT_DIR, 'keys.ts')}`);
}

main();
